"""Hand-computable negative-control witnesses for theory exploration."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

FloatArray = NDArray[np.float64]


@dataclass(frozen=True)
class StackedObservabilityResult:
    """Exact diagnostics for a collection of linear observation maps."""

    single_ranks: tuple[int, ...]
    stacked_rank: int
    stacked_eigenvalues: tuple[float, ...]
    direct_gramian_max_abs_error: float
    matches_expected: bool

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe representation."""

        return {
            "single_ranks": list(self.single_ranks),
            "stacked_rank": self.stacked_rank,
            "stacked_eigenvalues": list(self.stacked_eigenvalues),
            "direct_gramian_max_abs_error": self.direct_gramian_max_abs_error,
            "matches_expected": self.matches_expected,
        }


@dataclass(frozen=True)
class OrderEffectResult:
    """Diagnostics for swapping two fixed stochastic transition operators."""

    operator_a_row_stochastic: bool
    operator_b_row_stochastic: bool
    response_ab: float
    response_ba: float
    difference: float
    commutator_response: float
    matches_expected: bool

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe representation."""

        return {
            "operator_a_row_stochastic": self.operator_a_row_stochastic,
            "operator_b_row_stochastic": self.operator_b_row_stochastic,
            "response_ab": self.response_ab,
            "response_ba": self.response_ba,
            "difference": self.difference,
            "commutator_response": self.commutator_response,
            "matches_expected": self.matches_expected,
        }


def _float_array(value: object, *, name: str, ndim: int) -> FloatArray:
    array = np.asarray(value, dtype=np.float64)
    if array.ndim != ndim:
        raise ValueError(f"{name} must have {ndim} dimensions")
    if not np.isfinite(array).all():
        raise ValueError(f"{name} must be finite")
    return array


def stacked_observability_witness(
    matrices: list[object],
    *,
    expected_single_ranks: tuple[int, ...],
    expected_stacked_rank: int,
    expected_stacked_eigenvalues: tuple[float, ...],
    absolute_tolerance: float,
) -> StackedObservabilityResult:
    """Compare summed mechanism Gramians with the ordinary vertically stacked Gramian."""

    if not matrices:
        raise ValueError("at least one observation matrix is required")
    arrays = [_float_array(matrix, name=f"matrices[{index}]", ndim=2) for index, matrix in enumerate(matrices)]
    state_width = arrays[0].shape[1]
    if state_width == 0 or any(matrix.shape[1] != state_width for matrix in arrays):
        raise ValueError("all observation matrices must have the same nonzero state width")

    gramians = [matrix.T @ matrix for matrix in arrays]
    summed = np.sum(np.stack(gramians, axis=0), axis=0)
    vertically_stacked = np.vstack(arrays)
    direct = vertically_stacked.T @ vertically_stacked
    direct_error = float(np.max(np.abs(summed - direct)))
    single_ranks = tuple(int(np.linalg.matrix_rank(gramian)) for gramian in gramians)
    stacked_rank = int(np.linalg.matrix_rank(summed))
    eigenvalues = tuple(float(value) for value in np.linalg.eigvalsh(summed))

    matches_expected = (
        single_ranks == expected_single_ranks
        and stacked_rank == expected_stacked_rank
        and len(eigenvalues) == len(expected_stacked_eigenvalues)
        and np.allclose(eigenvalues, expected_stacked_eigenvalues, rtol=0.0, atol=absolute_tolerance)
        and direct_error <= absolute_tolerance
    )
    return StackedObservabilityResult(
        single_ranks=single_ranks,
        stacked_rank=stacked_rank,
        stacked_eigenvalues=eigenvalues,
        direct_gramian_max_abs_error=direct_error,
        matches_expected=bool(matches_expected),
    )


def _is_row_stochastic(operator: FloatArray, *, absolute_tolerance: float) -> bool:
    return bool(
        operator.ndim == 2
        and operator.shape[0] == operator.shape[1]
        and np.all(operator >= -absolute_tolerance)
        and np.allclose(
            operator.sum(axis=1),
            np.ones(operator.shape[0], dtype=np.float64),
            rtol=0.0,
            atol=absolute_tolerance,
        )
    )


def fixed_operator_order_witness(
    initial_distribution: object,
    operator_a: object,
    operator_b: object,
    observable: object,
    *,
    expected_ab: float,
    expected_ba: float,
    expected_difference: float,
    absolute_tolerance: float,
) -> OrderEffectResult:
    """Measure an order effect generated by two fixed, non-adaptive Markov operators."""

    initial = _float_array(initial_distribution, name="initial_distribution", ndim=1)
    matrix_a = _float_array(operator_a, name="operator_a", ndim=2)
    matrix_b = _float_array(operator_b, name="operator_b", ndim=2)
    target = _float_array(observable, name="observable", ndim=1)
    state_count = initial.shape[0]
    expected_shape = (state_count, state_count)
    if matrix_a.shape != expected_shape or matrix_b.shape != expected_shape or target.shape != (state_count,):
        raise ValueError("operators, distribution and observable must use the same state dimension")
    if not np.isclose(initial.sum(), 1.0, rtol=0.0, atol=absolute_tolerance) or np.any(
        initial < -absolute_tolerance
    ):
        raise ValueError("initial_distribution must be a probability vector")

    a_stochastic = _is_row_stochastic(matrix_a, absolute_tolerance=absolute_tolerance)
    b_stochastic = _is_row_stochastic(matrix_b, absolute_tolerance=absolute_tolerance)
    response_ab = float(initial @ matrix_a @ matrix_b @ target)
    response_ba = float(initial @ matrix_b @ matrix_a @ target)
    difference = response_ab - response_ba
    commutator_response = float(initial @ (matrix_a @ matrix_b - matrix_b @ matrix_a) @ target)
    matches_expected = (
        a_stochastic
        and b_stochastic
        and np.isclose(response_ab, expected_ab, rtol=0.0, atol=absolute_tolerance)
        and np.isclose(response_ba, expected_ba, rtol=0.0, atol=absolute_tolerance)
        and np.isclose(difference, expected_difference, rtol=0.0, atol=absolute_tolerance)
        and np.isclose(difference, commutator_response, rtol=0.0, atol=absolute_tolerance)
        and abs(difference) > absolute_tolerance
    )
    return OrderEffectResult(
        operator_a_row_stochastic=a_stochastic,
        operator_b_row_stochastic=b_stochastic,
        response_ab=response_ab,
        response_ba=response_ba,
        difference=difference,
        commutator_response=commutator_response,
        matches_expected=bool(matches_expected),
    )
