"""Versioned schema for the controlled-market truth asset (A-2 mechanism kernel).

Both arms use the same record grammar.  The treatment is strict FIFO versus uniform
sampling of *resting units* at the execution price.  Unit sampling is deliberate: an
actor cannot improve allocation probability merely by splitting one quantity across
several child orders.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from enum import StrEnum


class Side(StrEnum):
    BID = "B"
    ASK = "S"


class AllocationRule(StrEnum):
    FIFO = "fifo"
    RANDOM_UNIT_WITHIN_PRICE = "random_unit_within_price"


class RejectionReason(StrEnum):
    """Reason-coded order rejections; no free-text channel is part of the tape."""

    MALFORMED_REQUEST = "malformed_request"
    UNKNOWN_ACTOR = "unknown_actor"
    DUPLICATE_CLIENT_ID = "duplicate_client_id"
    PRICE_OUT_OF_BANDS = "price_out_of_bands"
    NEGATIVE_OR_ZERO_QUANTITY = "negative_or_zero_quantity"
    INVALID_CLOCKS = "invalid_clocks"
    SELF_TRADE_PREVENTED = "self_trade_prevented"
    INSUFFICIENT_CASH = "insufficient_cash"
    INSUFFICIENT_INVENTORY = "insufficient_inventory"
    INDUCED_BUY_CAPACITY_EXCEEDED = "induced_buy_capacity_exceeded"
    INDUCED_SELL_CAPACITY_EXCEEDED = "induced_sell_capacity_exceeded"


class CancelRejectionReason(StrEnum):
    UNKNOWN_ORDER = "unknown_order"
    NOT_OWNER = "not_owner"
    ALREADY_FILLED = "already_filled"
    ALREADY_CANCELLED = "already_cancelled"
    CANCEL_TOO_LATE = "cancel_too_late"
    INVALID_CLOCKS = "invalid_clocks"


class LatencyChoiceRejectionReason(StrEnum):
    UNKNOWN_ACTOR = "unknown_actor"
    DUPLICATE_CHOICE = "duplicate_choice"
    INVALID_INVESTMENT = "invalid_investment"
    INVALID_CLOCKS = "invalid_clocks"


class ReplaceRejectionReason(StrEnum):
    """Reason-coded replacement rejections; mirrors the cancel and order validation families."""

    UNKNOWN_ACTOR = "unknown_actor"
    UNKNOWN_ORDER = "unknown_order"
    NOT_OWNER = "not_owner"
    ORDER_NOT_RESTING = "order_not_resting"
    INVALID_CLOCKS = "invalid_clocks"
    DUPLICATE_CLIENT_ID = "duplicate_client_id"
    PRICE_OUT_OF_BANDS = "price_out_of_band"
    NEGATIVE_OR_ZERO_QUANTITY = "negative_or_zero_quantity"
    INSUFFICIENT_CASH = "insufficient_cash"
    INSUFFICIENT_INVENTORY = "insufficient_inventory"
    INDUCED_BUY_CAPACITY_EXCEEDED = "induced_buy_capacity_exceeded"
    INDUCED_SELL_CAPACITY_EXCEEDED = "induced_sell_capacity_exceeded"
    SELF_TRADE_PREVENTED = "self_trade_prevented"


class EventType(StrEnum):
    SESSION_START = "session_start"
    LATENCY_CHOICE = "latency_choice"
    LATENCY_CHOICE_REJECTED = "latency_choice_rejected"
    ORDER_REQUEST = "order_request"
    ORDER_ACCEPTED = "order_accepted"
    ORDER_REJECTED = "order_rejected"
    CANCEL_REQUEST = "cancel_request"
    ORDER_CANCELLED = "order_cancelled"
    CANCEL_REJECTED = "cancel_rejected"
    REPLACE_REQUEST = "replace_request"
    ORDER_REPLACED = "order_replaced"
    REPLACE_REJECTED = "replace_rejected"
    EXECUTION = "execution"
    SESSION_END = "session_end"


@dataclass(frozen=True)
class ThreeClocks:
    """Client decision, server receipt and matching timestamps in integer ticks."""

    client_ts: int
    receipt_ts: int
    match_ts: int


@dataclass(frozen=True)
class InformationRelease:
    """A public or induced-value information event fixed before a session starts."""

    tick: int
    label: str
    value: int


@dataclass(frozen=True)
class InitialOrder:
    """Resting order included in the replay prestate rather than generated by a request."""

    order_id: str
    actor: str
    side: Side
    price: int
    quantity: int


@dataclass(frozen=True)
class LatencyChoice:
    """Costly speed choice used by the treatment-native priority-rent module."""

    event_id: int
    actor: str
    round_id: int
    investment: int
    clocks: ThreeClocks


@dataclass(frozen=True)
class OrderRequest:
    """Aggressive or resting limit order; marketable limits cross on arrival."""

    event_id: int
    actor: str
    client_order_id: str
    side: Side
    price: int
    quantity: int
    clocks: ThreeClocks
    round_id: int = 0


@dataclass(frozen=True)
class CancelRequest:
    event_id: int
    actor: str
    order_id: str
    clocks: ThreeClocks
    round_id: int = 0


@dataclass(frozen=True)
class ReplaceRequest:
    """Atomic cancel-and-resubmit; the new order carries the parent lineage."""

    event_id: int
    actor: str
    replaces_order_id: str
    client_order_id: str
    side: Side
    price: int
    quantity: int
    clocks: ThreeClocks
    round_id: int = 0


@dataclass(frozen=True)
class Execution:
    """One maker fill; random-unit executions have quantity one by construction."""

    event_id: int
    execution_id: str
    aggressor_order_id: str
    maker_order_id: str
    maker_actor: str
    aggressor_actor: str
    side_of_aggressor: Side
    price: int
    quantity: int
    maker_remaining: int
    clocks: ThreeClocks
    round_id: int = 0


@dataclass(frozen=True)
class TapeRecord:
    """Universal event envelope with identity and anonymous state commitments."""

    sequence: int
    event_type: EventType
    payload: dict[str, object] = field(default_factory=dict)
    pre_state_hash: str = ""
    post_state_hash: str = ""
    pre_aggregate_state_hash: str = ""
    post_aggregate_state_hash: str = ""


@dataclass(frozen=True)
class SessionPrestate:
    """Everything fixed before requests that is needed to interpret and replay a session."""

    session_id: str
    seed: int
    allocation_rule: AllocationRule
    initial_cash: dict[str, int]
    initial_inventory: dict[str, int]
    price_bands: tuple[int, int]
    actors: tuple[str, ...]
    induced_buy_values: dict[str, tuple[int, ...]] = field(default_factory=dict)
    induced_sell_costs: dict[str, tuple[int, ...]] = field(default_factory=dict)
    information_schedule: tuple[InformationRelease, ...] = ()
    initial_book: tuple[InitialOrder, ...] = ()
    actor_roles: dict[str, str] = field(default_factory=dict)
    scheduler_seed: int = 0
    scheduler_tick: int = 0
    scheduler_state: str = "initial"
    assignment_key_commitment: str = "unassigned"
    latency_endowment: int = 0
    latency_delay_by_investment: tuple[int, ...] = ()
    schema_version: str = "lab-asset-v3"


def stable_hash(payload: object) -> str:
    """SHA-256 of a canonical JSON representation."""

    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def prestate_hash(prestate: SessionPrestate) -> str:
    return stable_hash(asdict(prestate))


def state_hash(
    *,
    prestate_digest: str,
    bids: dict[int, list[tuple[str, str, int]]],
    asks: dict[int, list[tuple[str, str, int]]],
    cash: dict[str, int],
    inventory: dict[str, int],
    units_bought: dict[str, int],
    units_sold: dict[str, int],
    realized_induced_surplus: dict[str, int],
    order_meta: dict[str, tuple[str, Side, int]],
    order_status: dict[str, str],
    used_client_ids: set[str],
    latency_choices: dict[tuple[int, str], int],
    order_parent: dict[str, str],
    sequence: int,
    order_counter: int,
    execution_counter: int,
    rejection_counter: int,
    last_match_ts: int,
    rng_state: object,
) -> str:
    """Full identity-layer state hash, including FIFO order and semantic RNG state."""

    def levels(book: dict[int, list[tuple[str, str, int]]]) -> list[list[object]]:
        return [
            [price, [[oid, actor, qty] for oid, actor, qty in book[price]]]
            for price in sorted(book)
        ]

    payload = {
        "prestate_hash": prestate_digest,
        "sequence": sequence,
        "bids": levels(bids),
        "asks": levels(asks),
        "cash": sorted(cash.items()),
        "inventory": sorted(inventory.items()),
        "units_bought": sorted(units_bought.items()),
        "units_sold": sorted(units_sold.items()),
        "realized_induced_surplus": sorted(realized_induced_surplus.items()),
        "order_meta": [
            [oid, actor, side.value, price]
            for oid, (actor, side, price) in sorted(order_meta.items())
        ],
        "order_status": sorted(order_status.items()),
        "used_client_ids": sorted(used_client_ids),
        "latency_choices": [
            [round_id, actor, investment]
            for (round_id, actor), investment in sorted(latency_choices.items())
        ],
        "order_parent": sorted(order_parent.items()),
        "order_counter": order_counter,
        "execution_counter": execution_counter,
        "rejection_counter": rejection_counter,
        "last_match_ts": last_match_ts,
        "rng_state": rng_state,
    }
    return stable_hash(payload)


def aggregate_state_hash(
    *,
    bids: dict[int, list[tuple[str, str, int]]],
    asks: dict[int, list[tuple[str, str, int]]],
    cash: dict[str, int],
    inventory: dict[str, int],
    last_match_ts: int,
) -> str:
    """Anonymous state hash used only at common request boundaries.

    Event-by-event hashes are not compared across arms because unit randomization can emit a
    different number of maker executions.  Under an exogenous, resource-slack request tape,
    this hash is equal after each completed request even when identity allocations differ.
    """

    def levels(book: dict[int, list[tuple[str, str, int]]]) -> list[list[int]]:
        return [[price, sum(qty for _, _, qty in book[price])] for price in sorted(book)]

    return stable_hash(
        {
            "bids": levels(bids),
            "asks": levels(asks),
            "total_cash": sum(cash.values()),
            "total_inventory": sum(inventory.values()),
            "last_match_ts": last_match_ts,
        }
    )


def record_to_json(record: TapeRecord) -> str:
    return json.dumps(asdict(record), sort_keys=True, separators=(",", ":"))


def prestate_to_json(prestate: SessionPrestate) -> str:
    return json.dumps(asdict(prestate), sort_keys=True, separators=(",", ":"))


def prestate_from_json(raw: str) -> SessionPrestate:
    data = json.loads(raw)
    return SessionPrestate(
        session_id=data["session_id"],
        seed=data["seed"],
        allocation_rule=AllocationRule(data["allocation_rule"]),
        initial_cash=data["initial_cash"],
        initial_inventory=data["initial_inventory"],
        price_bands=(data["price_bands"][0], data["price_bands"][1]),
        actors=tuple(data["actors"]),
        induced_buy_values={
            actor: tuple(values) for actor, values in data["induced_buy_values"].items()
        },
        induced_sell_costs={
            actor: tuple(values) for actor, values in data["induced_sell_costs"].items()
        },
        information_schedule=tuple(
            InformationRelease(
                tick=item["tick"], label=item["label"], value=item["value"]
            )
            for item in data["information_schedule"]
        ),
        initial_book=tuple(
            InitialOrder(
                order_id=item["order_id"],
                actor=item["actor"],
                side=Side(item["side"]),
                price=item["price"],
                quantity=item["quantity"],
            )
            for item in data["initial_book"]
        ),
        actor_roles=data["actor_roles"],
        scheduler_seed=data["scheduler_seed"],
        scheduler_tick=data["scheduler_tick"],
        scheduler_state=data["scheduler_state"],
        assignment_key_commitment=data["assignment_key_commitment"],
        latency_endowment=data["latency_endowment"],
        latency_delay_by_investment=tuple(data["latency_delay_by_investment"]),
        schema_version=data["schema_version"],
    )
