#!/usr/bin/env python3
"""D0-S2 corpus-generation driver for the ALPHA market cube (ops tooling).

NOT a frozen D0 file (freeze sha256 fd4a40b0...): this driver must CONFORM to
the frozen pins.  Remote execution only (PI compute rule 2026-09-06) -- never
run on the Mac beyond argument parsing.

Pin map (papers/proposal/, 2026-09-06):
  F1 sec.3 items 2/3/5/6 - R2 staging under alpha_cube_d0_20260921/, seed-file
                           sha256 binding, stage-receipt hash fields, immutable
                           corpus + resume rule (F1 sec.4: completed episodes
                           are never regenerated; a regenerated byte mismatch
                           vs the frozen stream manifest HALTS)
  F2 C1/C2(a)/C4/C5      - RNG tree, kernel-invariant request stream, FIFO
                           training truth, two aggregate conserving channels;
                           Annex C-2 seed supersession (11000+/12000+)
  F3 sec.1/sec.2.4/2.6   - F_exec pure selection, episode seed derivation
                           SeedSequence(root, spawn_key=(0, episode)), replay
                           gate incl. all four hashes, dual-arm CRN check
                           (identical post_aggregate_state_hash sequence at
                           order_accepted boundaries across kernels)
  E-1/E-4/E-5 receipts   - fexec_projector, conserving_emitter, frozen Hydra
                           configs + seed/stream manifest

Per (seed_root, episode_index):
  generate_episode -> build_prestate(kernel) -> ReferenceEngine submit* ->
  finish -> engine tape -> E-4 conserving channels + E-1 F_exec tensors.
Freeze-checklist instruments are HARD failures (F2 sec.8.3): the E-4 replay
guard (inside emit_conserving_channels), conservation_violations,
settlement_violations, and the E-1/E-4 round-grid agreement check.

Determinism discipline: no wall-clock, no timestamps, no RNG outside the
frozen derivations; every artifact and manifest is canonical JSON (sorted
keys, compact separators, single trailing newline); tape.jsonl lines are
record_to_json(record) + "\\n" (the verify_fixtures byte idiom).

PI-RATIFIED constants (decision record required before first execution):
  DRAW_SEED_TAG / episodes-per-seed are unpinned in every frozen authority
  (F1/F2/F3, E-5 manifest, freeze record); each is recorded verbatim in both
  manifest levels so the executed choice can be audited against the record.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import traceback
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Any

CORPUS_MANIFEST_SCHEMA = "ecomd-reexploration-d0s2-corpus-manifest-v1"
STREAM_MANIFEST_SCHEMA = "ecomd-reexploration-d0s2-stream-manifest-v1"
CAMPAIGN_ID = "alpha_cube_d0_20260919"  # E-5 manifest campaign_id (intentionally not the R2 date)
DGP_CONFIG_REL = Path("configs/reexploration/dgp")
SEED_MANIFEST_REL = Path(
    "experiments/reexploration/seed_stream_manifest_20260907/seeds_manifest.json"
)
A2_BUNDLE_ANCHOR = "fea8a136b0c3e19a00bddcb131a1540ca40fda6c1576dbc949001dbf76a9581c"  # F2 Annex C-4 canonical
A2_BUNDLE_REL = Path("experiments/lab_asset_a2/a2_exit_20260905/bundle_manifest.json")
DEFAULT_R2_PREFIX = "alpha_cube_d0_20260921/corpus/"
R2_REMOTE = "r2:ecophys"
# Frozen-pin enforcement (freeze commit f4e61bafe; commit-level fd4a40b0...):
# the driver hard-fails on any drift so a wrong checkout can never burn
# V100-h producing a G3-failing corpus.
FREEZE_COMMIT = "f4e61bafed21f12a6ec73dbe82b9ed4ea87bdd37"
FREEZE_FILE_PINS: dict[str, str] = {
    "configs/reexploration/dgp/lab_asset.yaml":
        "06b9691af333be8a6891ee1213032a785e61c03c3c26e8f8a4beb159b202c801",
    "experiments/reexploration/seed_stream_manifest_20260907/seeds_manifest.json":
        "361679c4a56e8e7fe7d393499ed22f5c9f61bef81706a1befa8ca7df27ea32f8",
    "scripts/lab_asset/dgp_request_generator.py":
        "2cef5a334cc7f0020459062e3f37d76aab55d4440c8a305e50a222bfd4d72152",
}
# PI-ratified 2026-09-21 (decision pi_d0s2_corpus_seed_pins_20260921):
# tag "draw" = the E-5-blessed derivation path; 64 = the F1 sec.0 cost basis.
DRAW_SEED_TAG = "draw"
DEFAULT_EPISODES = 64

_SURFACE: dict[str, Any] = {}


# ---------------------------------------------------------------- helpers


def canonical_bytes(obj: Any) -> bytes:
    return (json.dumps(obj, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def ensure_repo(repo_root: Path) -> None:
    for entry in (str(repo_root), str(repo_root / "scripts")):
        if entry not in sys.path:
            sys.path.insert(0, entry)


def enforce_freeze_pins(repo_root: Path) -> None:
    """Hard-fail on any drift vs the executed D0 freeze (checker defect 4)."""

    for rel, expected in FREEZE_FILE_PINS.items():
        path = repo_root / rel
        if not path.is_file():
            raise SystemExit(f"freeze-pin file missing: {rel}")
        actual = sha256_file(path)
        if actual != expected:
            raise SystemExit(
                f"freeze-pin mismatch: {rel}\n  expected {expected}\n  actual   {actual}\n"
                "checkout drifted from the frozen D0 state -- refusing to generate"
            )
    probe = subprocess.run(
        ["git", "-C", str(repo_root), "merge-base", "--is-ancestor", FREEZE_COMMIT, "HEAD"],
        capture_output=True,
    )
    if probe.returncode != 0:
        head = git_head(repo_root)
        raise SystemExit(
            f"checkout HEAD {head} does not descend from the freeze commit {FREEZE_COMMIT} "
            "-- refusing to generate"
        )
    anchor_path = repo_root / A2_BUNDLE_REL
    if anchor_path.is_file():
        actual = sha256_file(anchor_path)
        if actual != A2_BUNDLE_ANCHOR:
            raise SystemExit(
                f"A-2 bundle anchor mismatch: {A2_BUNDLE_REL}\n  expected {A2_BUNDLE_ANCHOR}\n"
                f"  actual   {actual}"
            )


def load_surface(repo_root: Path) -> dict[str, Any]:
    """Import the repo modules once per process (sys.path setup included)."""

    if _SURFACE:
        return _SURFACE
    ensure_repo(repo_root)
    from lab_asset import dgp_request_generator as dgp
    from lab_asset.conserving_emitter import (
        conservation_violations,
        emit_conserving_channels,
        settlement_violations,
    )
    from lab_asset.matching import ReferenceEngine
    from lab_asset.replay import replay
    from lab_asset.schema import (
        AllocationRule,
        prestate_from_json,
        prestate_to_json,
        record_to_json,
    )
    from lab_asset.verify_fixtures import load_tape
    from ecomd.corpus.fexec_projector import project_fexec_corpus

    _SURFACE.update(
        dgp=dgp,
        conservation_violations=conservation_violations,
        emit_conserving_channels=emit_conserving_channels,
        settlement_violations=settlement_violations,
        ReferenceEngine=ReferenceEngine,
        replay=replay,
        AllocationRule=AllocationRule,
        prestate_from_json=prestate_from_json,
        prestate_to_json=prestate_to_json,
        record_to_json=record_to_json,
        load_tape=load_tape,
        project_fexec_corpus=project_fexec_corpus,
    )
    return _SURFACE


def stream_dir(out_dir: Path, family: str, axis: str, kernel: str, seed_root: int) -> Path:
    return out_dir / family / f"axis_{axis}" / f"kernel_{kernel}" / f"seed_{seed_root:06d}"


def episode_dir(sdir: Path, episode_index: int) -> Path:
    return sdir / f"episode_{episode_index:04d}"


def git_head(repo_root: Path) -> str | None:
    try:
        return subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except Exception:
        return None


def fexec_payload(corpus: Any) -> dict[str, Any]:
    """JSON form of an E-1 FexecCorpus (tensors via tolist; float repr is
    CPython-shortest and stable across nodes for identical doubles)."""

    return {
        "session_id": corpus.session_id,
        "allocation_rule": corpus.allocation_rule,
        "seed": corpus.seed,
        "n_slots": corpus.n_slots,
        "dtype": str(corpus.features.dtype),
        "match_ticks": list(corpus.match_ticks),
        "n_executions": corpus.n_executions,
        "features": corpus.features.tolist(),
        "channels_delta": corpus.channels_delta.tolist(),
        "channels_cumulative": corpus.channels_cumulative.tolist(),
        "slot_prices": corpus.slot_prices.tolist(),
        "slot_quantities": corpus.slot_quantities.tolist(),
        "tape_hash": corpus.tape_hash,
        "content_hash": corpus.content_hash,
        "corpus_hash": corpus.corpus_hash,
    }


# ---------------------------------------------------------------- generation


def generate_episode_artifacts(surface: dict[str, Any], job: dict[str, Any],
                               episode_index: int) -> dict[str, Any]:
    dgp = surface["dgp"]
    seed_root = job["seed_root"]
    cfg = dgp.config_for_axis(dgp.config_from_mapping(job["config"]), job["axis"])
    stream = dgp.generate_episode(seed_root, episode_index, cfg)
    episode_sha = sha256_bytes(dgp.episode_canonical_json(stream))
    draw_seed = dgp.derive_seed(seed_root, DRAW_SEED_TAG, episode_index)
    prestate = dgp.build_prestate(stream, surface["AllocationRule"](job["kernel"]), draw_seed)

    engine = surface["ReferenceEngine"](prestate)
    for request in dgp.order_requests(stream):
        engine.submit(request)
    engine.finish()
    tape = engine.tape

    # E-4 (replay guard enforced inside emit_conserving_channels)
    series = surface["emit_conserving_channels"](prestate, tape)
    violations = surface["conservation_violations"](series)
    settlement = surface["settlement_violations"](prestate, tape, series)
    if violations or settlement:
        raise RuntimeError(
            f"conservation/settlement gate failed (F2 sec.8.3 instrument) "
            f"seed_root={seed_root} episode={episode_index}: {violations + settlement}"
        )

    # E-1 + cross-item grid agreement (cheap per-session assert, E-1/E-4 contract)
    corpus = surface["project_fexec_corpus"](prestate, tape, seed_root)
    if corpus.channels_delta.tolist() != series.increment_matrix():
        raise RuntimeError(
            f"E-1/E-4 round-grid disagreement seed_root={seed_root} "
            f"episode={episode_index}"
        )

    edir = episode_dir(
        stream_dir(Path(job["out_dir"]), job["family"], job["axis"], job["kernel"], seed_root),
        episode_index,
    )
    edir.mkdir(parents=True, exist_ok=True)
    blobs = {
        "prestate.json": (surface["prestate_to_json"](prestate) + "\n").encode("utf-8"),
        "tape.jsonl": "".join(
            surface["record_to_json"](record) + "\n" for record in tape
        ).encode("utf-8"),
        "channels.json": (series.to_json() + "\n").encode("utf-8"),
        "fexec_corpus.json": canonical_bytes(fexec_payload(corpus)),
    }
    files = {}
    for name, blob in blobs.items():
        (edir / name).write_bytes(blob)
        files[name] = sha256_bytes(blob)
    return {
        "episode_index": episode_index,
        "draw_seed": draw_seed,
        "session_id": prestate.session_id,
        "prestate_hash": tape[0].payload["prestate_hash"],
        "episode_canonical_json_sha256": episode_sha,
        "config_fingerprint": dgp.config_fingerprint(cfg),
        "files": files,
        "n_records": len(tape),
        "n_rounds": len(corpus.rounds),
        "n_executions": corpus.n_executions,
        "tape_hash": corpus.tape_hash,
        "content_hash": corpus.content_hash,
        "corpus_hash": corpus.corpus_hash,
        "conservation_violations": len(violations),
        "settlement_violations": len(settlement),
        "e1_e4_grid_match": True,
    }


def entry_files_verify(edir: Path, entry: dict[str, Any]) -> bool:
    for name, expected in sorted(entry["files"].items()):
        path = edir / name
        if not path.is_file() or sha256_file(path) != expected:
            return False
    return True


def process_stream(job: dict[str, Any]) -> dict[str, Any]:
    """One seed root = one embarrassingly parallel stream (unit of work)."""

    surface = load_surface(Path(job["repo_root"]))
    out_dir = Path(job["out_dir"])
    sdir = stream_dir(out_dir, job["family"], job["axis"], job["kernel"], job["seed_root"])
    previous: dict[int, dict[str, Any]] = {}
    prev_path = sdir / "stream_manifest.json"
    if prev_path.is_file():
        previous = {
            int(e["episode_index"]): e
            for e in json.loads(prev_path.read_text())["episodes"]
        }

    entries: list[dict[str, Any]] = []
    for episode_index in range(job["episodes"]):
        prior = previous.get(episode_index)
        edir = episode_dir(sdir, episode_index)
        if prior is not None and entry_files_verify(edir, prior):
            entries.append(prior)  # F1 sec.4: completed episodes never regenerate
            continue
        if job["manifest_only"]:
            raise RuntimeError(
                f"manifest-only: missing or unverified artifacts for {edir}; "
                "run generation first"
            )
        entry = generate_episode_artifacts(surface, job, episode_index)
        if prior is not None and entry["files"] != prior["files"]:
            # F1 sec.4 halt: regenerated bytes differ from the frozen stream
            # manifest -- nondeterminism or tampering, never silently relaundered.
            raise RuntimeError(
                f"{edir}: regenerated bytes differ from the frozen stream "
                "manifest (F1 sec.4 halt)"
            )
        entries.append(entry)

    manifest = {
        "schema_version": STREAM_MANIFEST_SCHEMA,
        "campaign_id": CAMPAIGN_ID,
        "stage": "D0-S2",
        "seed_root": job["seed_root"],
        "namespace": job["namespace"],
        "family": job["family"],
        "axis": job["axis"],
        "kernel": job["kernel"],
        "dgp_config_fingerprint": job["config_fingerprint"],
        "episodes_per_seed": job["episodes"],
        "draw_seed_rule": f'derive_seed(seed_root, "{DRAW_SEED_TAG}", episode_index)',
        "episodes": entries,
    }
    sdir.mkdir(parents=True, exist_ok=True)
    manifest_path = sdir / "stream_manifest.json"
    manifest_path.write_bytes(canonical_bytes(manifest))
    return {
        "seed_root": job["seed_root"],
        "namespace": job["namespace"],
        "n_episodes": len(entries),
        "n_records": sum(e["n_records"] for e in entries),
        "n_rounds": sum(e["n_rounds"] for e in entries),
        "n_executions": sum(e["n_executions"] for e in entries),
        "manifest": manifest_path.relative_to(out_dir).as_posix(),
        "manifest_sha256": sha256_file(manifest_path),
    }


# ---------------------------------------------------------------- validation


def boundary_aggregate_hashes(tape_path: Path) -> list[str] | None:
    """post_aggregate_state_hash sequence at order_accepted boundaries
    (F3 sec.2.6 item 3 dual-arm CRN surface); None when unreadable."""

    values: list[str] = []
    for line in tape_path.read_text().splitlines():
        if not line.strip():
            continue
        raw = json.loads(line)
        if raw.get("event_type") == "order_accepted":
            values.append(raw.get("post_aggregate_state_hash", ""))
    return values


def validate_stream(job: dict[str, Any]) -> dict[str, Any]:
    """Byte-exact re-derivation + replay validation (F1 sec.3 item 2, F3 2.6).

    Per episode: (i) re-derive the episode and compare episode_canonical_json
    sha256; (ii) re-derive prestate and compare prestate.json bytes; (iii)
    re-execute the engine and compare tape.jsonl bytes; (iv) re-run E-4/E-1
    and compare channels.json / fexec_corpus.json bytes; (v) replay-validate
    the DISK prestate/tape via lab_asset.replay.replay (record-by-record incl.
    all four hashes); (vi) re-verify every artifact sha256 against the stream
    manifest entry. Cross-arm: when the sibling kernel tree exists, assert
    stream identity and the order_accepted aggregate-hash CRN sequence.
    """

    surface = load_surface(Path(job["repo_root"]))
    dgp = surface["dgp"]
    seed_root = job["seed_root"]
    sdir = stream_dir(Path(job["out_dir"]), job["family"], job["axis"], job["kernel"], seed_root)
    failures: list[str] = []
    manifest_path = sdir / "stream_manifest.json"
    if not manifest_path.is_file():
        return {"seed_root": seed_root, "n_episodes": 0,
                "failures": [f"missing {manifest_path}"]}
    manifest = json.loads(manifest_path.read_text())
    for key in ("kernel", "axis", "family"):
        if manifest[key] != job[key]:
            failures.append(f"stream manifest {key}={manifest[key]} != cli {job[key]}")
    if manifest["dgp_config_fingerprint"] != job["config_fingerprint"]:
        failures.append("stream manifest dgp_config_fingerprint != cli config fingerprint")
    if manifest["episodes_per_seed"] != job["episodes"]:
        failures.append(
            f"stream manifest episodes_per_seed={manifest['episodes_per_seed']} "
            f"!= cli {job['episodes']} (a wrong --episodes-per-seed silently "
            "validates a subset)"
        )
    cfg = dgp.config_for_axis(dgp.config_from_mapping(job["config"]), job["axis"])

    sibling_kernel = (
        "random_unit_within_price" if job["kernel"] == "fifo" else "fifo"
    )
    sibling_dir = stream_dir(
        Path(job["out_dir"]), job["family"], job["axis"], sibling_kernel, seed_root
    )

    for entry in manifest["episodes"]:
        episode_index = int(entry["episode_index"])
        edir = episode_dir(sdir, episode_index)
        label = f"seed_root={seed_root} episode={episode_index}"
        for name, expected in sorted(entry["files"].items()):
            path = edir / name
            if not path.is_file() or sha256_file(path) != expected:
                failures.append(f"{label}: artifact hash mismatch {name}")

        stream = dgp.generate_episode(seed_root, episode_index, cfg)
        if sha256_bytes(dgp.episode_canonical_json(stream)) != entry["episode_canonical_json_sha256"]:
            failures.append(f"{label}: episode_canonical_json re-derivation mismatch")
            continue
        prestate = dgp.build_prestate(
            stream, surface["AllocationRule"](manifest["kernel"]), entry["draw_seed"]
        )
        expected_prestate = (surface["prestate_to_json"](prestate) + "\n").encode("utf-8")
        if not (edir / "prestate.json").is_file() or (edir / "prestate.json").read_bytes() != expected_prestate:
            failures.append(f"{label}: prestate re-derivation mismatch")

        engine = surface["ReferenceEngine"](prestate)
        for request in dgp.order_requests(stream):
            engine.submit(request)
        engine.finish()
        regenerated = "".join(
            surface["record_to_json"](record) + "\n" for record in engine.tape
        ).encode("utf-8")
        if not (edir / "tape.jsonl").is_file() or (edir / "tape.jsonl").read_bytes() != regenerated:
            failures.append(f"{label}: tape re-derivation mismatch")

        series = surface["emit_conserving_channels"](prestate, engine.tape)
        expected_channels = (series.to_json() + "\n").encode("utf-8")
        if not (edir / "channels.json").is_file() or (edir / "channels.json").read_bytes() != expected_channels:
            failures.append(f"{label}: channels re-derivation mismatch")
        corpus = surface["project_fexec_corpus"](prestate, engine.tape, seed_root)
        expected_fexec = canonical_bytes(fexec_payload(corpus))
        if not (edir / "fexec_corpus.json").is_file() or (edir / "fexec_corpus.json").read_bytes() != expected_fexec:
            failures.append(f"{label}: fexec_corpus re-derivation mismatch")

        disk_prestate = surface["prestate_from_json"]((edir / "prestate.json").read_text())
        disk_tape = surface["load_tape"](edir / "tape.jsonl")
        report = surface["replay"](disk_prestate, disk_tape)
        if not report.ok:
            failures.append(
                f"{label}: replay FAILED at sequence {report.first_mismatch_sequence}"
            )

        # F3 sec.2.6 item 3: dual-arm CRN across kernels on the same request stream
        sibling_tape = episode_dir(sibling_dir, episode_index) / "tape.jsonl"
        sibling_manifest = sibling_dir / "stream_manifest.json"
        if sibling_tape.is_file() and sibling_manifest.is_file():
            sibling_entries = {
                int(e["episode_index"]): e
                for e in json.loads(sibling_manifest.read_text())["episodes"]
            }
            sibling_entry = sibling_entries.get(episode_index)
            if sibling_entry is None:
                failures.append(f"{label}: sibling kernel tree missing episode entry")
            else:
                if sibling_entry["episode_canonical_json_sha256"] != entry["episode_canonical_json_sha256"]:
                    failures.append(f"{label}: sibling kernel stream identity broken")
                mine = boundary_aggregate_hashes(edir / "tape.jsonl")
                theirs = boundary_aggregate_hashes(sibling_tape)
                if not mine or not theirs:
                    failures.append(
                        f"{label}: CRN check found no order_accepted boundaries "
                        "(boundary extraction broken)"
                    )
                elif mine != theirs:
                    failures.append(
                        f"{label}: dual-arm CRN violation -- post_aggregate_state_hash "
                        "sequence diverges across kernels at order_accepted boundaries"
                    )
    return {"seed_root": seed_root, "n_episodes": len(manifest["episodes"]),
            "failures": failures}


# ---------------------------------------------------------------- main


def parse_seed_range(text: str) -> range:
    start_text, stop_text = text.split(":")
    start, stop = int(start_text), int(stop_text)
    if stop <= start:
        raise argparse.ArgumentTypeError("seed range must be start < stop (half-open)")
    return range(start, stop)


def run_pool(jobs: list[dict[str, Any]], workers: int, fn) -> tuple[list[dict[str, Any]], list[str]]:
    results: list[dict[str, Any]] = []
    failures: list[str] = []
    if workers <= 1:
        for job in jobs:
            try:
                results.append(fn(job))
                print(f"stream seed_root={job['seed_root']}: done", flush=True)
            except Exception:
                failures.append(f"seed_root={job['seed_root']}\n{traceback.format_exc()}")
        return results, failures
    with ProcessPoolExecutor(max_workers=workers) as pool:
        futures = {pool.submit(fn, job): job["seed_root"] for job in jobs}
        for future in as_completed(futures):
            seed_root = futures[future]
            try:
                results.append(future.result())
                print(f"stream seed_root={seed_root}: done", flush=True)
            except Exception:
                failures.append(f"seed_root={seed_root}\n{traceback.format_exc()}")
    return results, failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="D0-S2 D1 corpus generation driver (conforms to the frozen D0 pins)"
    )
    parser.add_argument("--repo-root", default=os.environ.get("ECOPHYS_ROOT") or str(Path.cwd()),
                        help="EcoPhys checkout root (default: $ECOPHYS_ROOT or cwd)")
    parser.add_argument("--seed-root-range", required=True, type=parse_seed_range,
                        help="half-open root range, e.g. 11000:11030 (30 roots)")
    parser.add_argument("--family", default="lab_asset", choices=["lab_asset"],
                        help="D0-S2 scope is lab_asset only; D2 families are Stage-2 (F2 C16 item 13)")
    parser.add_argument("--axis", default="id", choices=["id", "pop_2x", "tick_2x"],
                        help="kswap shares the id corpus (E-5 AXIS_SPECS: dgp_axis=id)")
    parser.add_argument("--kernel", default="fifo",
                        choices=["fifo", "random_unit_within_price"],
                        help="dual-arm corpus: run once per kernel (F1 D0-S2 row)")
    parser.add_argument("--episodes-per-seed", type=int, required=True,
                        help="UNPINNED in F1/F2/F3 and the E-5 manifest -- PI-ratified value "
                             "required explicitly; recorded verbatim in both manifests")
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--r2-prefix", default=DEFAULT_R2_PREFIX)
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--manifest-only", action="store_true",
                        help="rebuild manifests from existing verified artifacts; never generate")
    parser.add_argument("--validate", action="store_true",
                        help="byte-exact re-derivation + replay validation of an existing corpus")
    parser.add_argument("--pip-freeze", default=None,
                        help="path to a pip-freeze snapshot; sha256 recorded (F1 sec.3 item 6)")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    if not (repo_root / "scripts" / "lab_asset").is_dir():
        print(f"repo root not found: {repo_root}", file=sys.stderr)
        return 1
    if args.episodes_per_seed < 1:
        print("--episodes-per-seed must be >= 1", file=sys.stderr)
        return 1
    enforce_freeze_pins(repo_root)

    roots = list(args.seed_root_range)
    seed_manifest_path = repo_root / SEED_MANIFEST_REL
    if not seed_manifest_path.is_file():
        print(f"frozen seed manifest missing: {seed_manifest_path}", file=sys.stderr)
        return 1
    seed_doc = json.loads(seed_manifest_path.read_text())
    namespaces = {int(r["seed"]): r["namespace"] for r in seed_doc.get("seed_roots", [])}
    unknown = [r for r in roots if r not in namespaces]
    if unknown:
        print(f"seed roots absent from the frozen E-5 manifest: {unknown}", file=sys.stderr)
        return 1

    surface = load_surface(repo_root)
    dgp = surface["dgp"]
    config_path = repo_root / DGP_CONFIG_REL / f"{args.family}.yaml"
    if not config_path.is_file():
        print(f"DGP config missing: {config_path}", file=sys.stderr)
        return 1
    import yaml  # repo env dependency (Hydra/OmegaConf config tree)

    config = yaml.safe_load(config_path.read_text())["config"]
    cfg = dgp.config_for_axis(dgp.config_from_mapping(config), args.axis)
    out_dir = Path(args.out_dir).resolve()

    jobs = [
        {
            "repo_root": str(repo_root),
            "out_dir": str(out_dir),
            "family": args.family,
            "axis": args.axis,
            "kernel": args.kernel,
            "config": config,
            "config_fingerprint": dgp.config_fingerprint(cfg),
            "seed_root": seed_root,
            "namespace": namespaces[seed_root],
            "episodes": args.episodes_per_seed,
            "manifest_only": args.manifest_only,
        }
        for seed_root in roots
    ]

    if args.validate:
        results, failures = run_pool(jobs, args.workers, validate_stream)
        for result in sorted(results, key=lambda r: r["seed_root"]):
            status = "OK" if not result["failures"] else f"{len(result['failures'])} FAILURES"
            print(f"validate seed_root={result['seed_root']}: "
                  f"episodes={result['n_episodes']} {status}")
            for line in result["failures"]:
                print(f"  {line}")
        for block in failures:
            print(block, file=sys.stderr)
        total_bad = sum(len(r["failures"]) for r in results) + len(failures)
        print(f"d0s2_validate={'PASS' if total_bad == 0 else 'FAIL'} ({total_bad} failures)")
        return 0 if total_bad == 0 else 1

    summaries, failures = run_pool(jobs, args.workers, process_stream)
    for block in failures:
        print(block, file=sys.stderr)
    if failures:
        return 1
    summaries.sort(key=lambda s: s["seed_root"])

    campaign = {
        "schema_version": CORPUS_MANIFEST_SCHEMA,
        "campaign_id": CAMPAIGN_ID,
        "stage": "D0-S2",
        "driver": {
            "sha256": sha256_file(Path(__file__).resolve())
            if Path(__file__).is_file() else None,
            "git_head": git_head(repo_root),
            "pip_freeze_sha256": sha256_file(Path(args.pip_freeze).resolve())
            if args.pip_freeze else None,
        },
        "freeze_binding": {
            "freeze_commit": FREEZE_COMMIT,
            "commit_level_freeze_sha256": "fd4a40b0306d415cef9a8a41b8e94e5afb21126e4e3d7ff99097e066f9981f57",
            "file_pins_enforced": {rel: expected for rel, expected in FREEZE_FILE_PINS.items()},
            "a2_bundle_anchor_verified": (repo_root / A2_BUNDLE_REL).is_file(),
        },
        "dgp": {
            "family": args.family,
            "axis": args.axis,
            "kernel": args.kernel,
            "config_path": config_path.relative_to(repo_root).as_posix(),
            "config_sha256": sha256_file(config_path),
            "config_fingerprint": dgp.config_fingerprint(cfg),
        },
        "seed_manifest": {
            "path": SEED_MANIFEST_REL.as_posix(),
            "sha256": sha256_file(seed_manifest_path),
        },
        "a2_bundle_anchor": A2_BUNDLE_ANCHOR,
        "episodes_per_seed": args.episodes_per_seed,
        "episodes_pin_status": (
            "PI-ratified CLI value; NOT numerically pinned in F1/F2/F3 or the "
            "E-5 seed/stream manifest (ratification decision recorded under "
            "research/discovery/decisions/)"
        ),
        "draw_seed_rule": f'derive_seed(seed_root, "{DRAW_SEED_TAG}", episode_index)',
        "r2_prefix": args.r2_prefix,
        "totals": {
            "n_streams": len(summaries),
            "n_episodes": sum(s["n_episodes"] for s in summaries),
            "n_records": sum(s["n_records"] for s in summaries),
            "n_rounds": sum(s["n_rounds"] for s in summaries),
            "n_executions": sum(s["n_executions"] for s in summaries),
        },
        "streams": [
            {
                "seed_root": s["seed_root"],
                "namespace": s["namespace"],
                "n_episodes": s["n_episodes"],
                "n_records": s["n_records"],
                "n_rounds": s["n_rounds"],
                "n_executions": s["n_executions"],
                "manifest": s["manifest"],
                "manifest_sha256": s["manifest_sha256"],
            }
            for s in summaries
        ],
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "corpus_manifest.json").write_bytes(canonical_bytes(campaign))

    dest = R2_REMOTE + "/" + args.r2_prefix.rstrip("/")
    print(f"campaign manifest: {out_dir / 'corpus_manifest.json'}")
    print(f"totals: {campaign['totals']}")
    print("# upload (NOT auto-run; F1 sec.3 item 2 staging is immutable once written):")
    print(f"rclone copy {out_dir} {dest} --checksum")
    print(f"rclone check {out_dir} {dest} --checksum")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
