create table if not exists public.checkpoints (
    id bigint generated by default as identity primary key,
    local_path text not null,
    r2_bucket text not null,
    r2_key text not null,
    size_bytes bigint not null check (size_bytes >= 0),
    sha256 text not null check (length(sha256) = 64),
    experiment_dir text not null,
    result_dir text not null,
    checkpoint_name text not null,
    seed integer,
    target_dataset text,
    target_period text,
    n_agents integer,
    config jsonb,
    training_summary jsonb,
    uploaded_at timestamptz,
    upload_status text not null default 'pending',
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (r2_bucket, r2_key)
);

create index if not exists checkpoints_experiment_dir_idx
    on public.checkpoints (experiment_dir);

create index if not exists checkpoints_sha256_idx
    on public.checkpoints (sha256);

create index if not exists checkpoints_target_dataset_idx
    on public.checkpoints (target_dataset);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists checkpoints_set_updated_at on public.checkpoints;

create trigger checkpoints_set_updated_at
before update on public.checkpoints
for each row
execute function public.set_updated_at();
